10600 marker navigation
NSU-PinMap/PinMap pull request #2
Opened 2023-11-03 04:15 UTC by VTsarevNSU

issue готово:
по нажатию на маркер открывается редактирование
по нажатию на кнопку с плюсом, а затем на кнопку с галочкой открывается создание + ставится локальный маркер в центр экрана

2023-11-04 15:37 UTC, v-kharchenko commented
### Качество кода 
- В строке 24: REQUEST_PERMISSIONS_REQUEST_CODE - непонятное название константы.
- Функция onCreate() - сложная для восприятия.  По возможности вынести части в отдельные функции, например инициализацию листенеров кнопок. Комментарии, поясняющие суть блока кода, предпочтительно заменить вызовом функции, название которой отражало бы эту суть. Если блок кода читается просто и не требует вынесения в отдельную функцию, лучше комментарии так же убрать.
- Убрать комментарии с информацией об OSMdroid и с закомментированным кодом, который непонятно будет ли использоваться. Если код будет использоваться, раскомментировать и поставить "заглушки".
- Также убрать комментарии на английском от самого OSMdroid.
- MainActivity лучше переименовать в MapActivity.

### Функциональности
- Карту предпочтительно реализовать как фрагмент.
- PinEditActivity и PinCreateActivity удалить, в точках их вызова заменить на Toast и пометить комментарием // TODO: Вызывать PinConstructorActivity
- При тестировании на моём устройстве кнопки не всегда реагируют на нажатие. Стоит вынести на проверку и багфикс.
- Попробовать найти альтернативу deprecated-функциям.

2023-11-04 15:40 UTC, v-kharchenko requested changes
### Функциональности
- Карту предпочтительно реализовать как фрагмент.
- PinEditActivity и PinCreateActivity удалить, в точках их вызова заменить на Toast и пометить комментарием // TODO: Вызывать PinConstructorActivity
- При тестировании на моём устройстве кнопки не всегда реагируют на нажатие. Стоит вынести на проверку и багфикс.
- Попробовать найти альтернативу deprecated-функциям.

### Качество кода
- В строке 24: REQUEST_PERMISSIONS_REQUEST_CODE - непонятное название константы.
- Функция onCreate() - сложная для восприятия. По возможности вынести части в отдельные функции, например инициализацию листенеров кнопок. Комментарии, поясняющие суть блока кода, предпочтительно заменить вызовом функции, название которой отражало бы эту суть. Если блок кода читается просто и не требует вынесения в отдельную функцию, лучше комментарии так же убрать.
- Убрать комментарии с информацией об OSMdroid и с закомментированным кодом, который непонятно будет ли использоваться. Если код будет использоваться, раскомментировать и поставить "заглушки".
- Также убрать комментарии на английском от самого OSMdroid.
- MainActivity лучше переименовать в MapActivity.

2023-11-05 09:19 UTC, v-kharchenko approved these changes
- Задачу 10600 считаю выполненной вместе с доп. требованиями.
- Предлагаю вынести перенос карты из активити во фрагмент в новую задачу.
- Также стоит отдельно вынести исправление бага: на Android SDK 33 кнопки реагируют не на каждое нажатие.

2023-11-05 11:31 UTC, DoHKapJleoHe approved these changes

2023-11-05 11:44 UTC, AliceDarkmoon55 approved these changes

2023-11-05 16:32 UTC, merged