10849 database
NSU-PinMap/PinMap pull request #4
Opened 2023-11-12 13:32 UTC by MatusNatalia

хз работает оно или нет...

2023-11-13 09:12 UTC, VTsarevNSU approved these changes
ok cool

2023-11-13 09:38 UTC, v-kharchenko commented on app/src/main/java/ru/nsu/ccfit/tsd/pinmap/database/daos/PinDao.kt
> +    fun isPinExists(id : Int) : Boolean
Кажется стоит заменить на doesPinExist

2023-11-13 09:41 UTC, v-kharchenko commented on app/src/main/java/ru/nsu/ccfit/tsd/pinmap/pins/SQLitePinStorage.kt
> +class SQLitePinStorage(val db : PinMapDatabase) : PinStorage {
Стоит переместить в пакет database (пакет инкапсулирует реализацию PinStorage для работы с SQLite)

2023-11-13 09:46 UTC, v-kharchenko requested changes
- Пул-реквест перевести на ветку "dev"
- Поправить согласно комментам

2023-11-15 05:09 UTC, DoHKapJleoHe approved these changes

2023-11-19 15:39 UTC, v-kharchenko approved these changes

2023-11-19 15:40 UTC, merged